#
# AddTool.java
#
addComponentAction = Add %s
addToolText = Add %s
circularError = Cannot add a subcircuit that uses this circuit, as it creates a circular reference.
negativeCoordError = Component cannot have negative coordinates.
MatrixPlacerException = Base label either has wrong syntax or is already contained in the circuit.
#
# EditTool.java
#
editTool = Edit
editToolDesc = Select, move and wire components
selectionRefaceAction = Change Selection Direction
#
# LibraryTools.java
#
LibLoadErrors = Errors occurred loading library:
LibraryHasDuplicatedSublibraries = Library contains duplicated sub-libraries:
LibraryHasDuplicatedTools = Library contains multiple instances of tool:
#
# MenuTool.java
#
compDeleteItem = Delete
compRotateRight = Rotate Right
compRotateLeft = Rotate Left
compShowAttrItem = Show Properties
menuTool = Component menu
menuToolDesc = Open a component’s own menu
rotateComponentAction = Rotate %s
selCopyItem = Copy Selection
selCutItem = Cut Selection
selDeleteItem = Delete Selection
#
# PokeTool.java
#
pokeTool = Interact
pokeToolDesc = Change values in the running circuit
#
# SelectTool.java
#
cannotModifyError = Cannot modify circuit.
changeComponentAttributesAction = Change Properties
exclusiveError = Conflicting component already there.
moveWorkingMsg = Computing connections…
selectTool = Select
selectToolDesc = Select and move components
#
# TextTool.java
#
removeComponentAction = Remove %s
textTool = Text
textToolDesc = Add and edit labels
#
# WiringTool.java
#
addWireAction = Add Wire
addWiresAction = Add Wires
shortenWireAction = Shorten Wire
wiringTool = Wire
wiringToolDesc = Draw wires between components
