#
# Control file to build the Logisim Revolution Snap package
# https://git.briggen.dev/NilsBriggen/Logisim-Revolution
# https://snapcraft.io/
#
# Marcin Orlowski
#

name: logisim-revolution
title: Logisim Revolution
summary: Digital logic design tool and simulator
description: |
 Logisim Revolution is educational software for designing and simulating digital logic circuits.
 Logisim Revolution is free, open-source, and cross-platform.

 Project highlights:
  * easy to use circuit designer,
  * logic circuit simulations,
  * chronogram (to see the evolution of signals in your circuit),
  * electronic board integration (schematics can be simulated on real hardware),
  * VHDL components (components behavior can be specified in VHDL!),
  * TCL/TK console (interfaces between the circuit and the user),
  * huge library of components (LEDs, TTLs, switches, SoCs),
  * supports multiple languages,
  * and more!
website: https://git.briggen.dev/NilsBriggen/Logisim-Revolution
contact: https://git.briggen.dev/NilsBriggen/Logisim-Revolution/issues
issues: https://git.briggen.dev/NilsBriggen/Logisim-Revolution/issues
source-code: https://git.briggen.dev/NilsBriggen/Logisim-Revolution
license: GPL-3.0
adopt-info: logisim-revolution
icon: snap/gui/logisim-revolution-icon-128.png

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
  arm64:

apps:
  logisim-revolution:
    extensions: [gnome]
    command: usr/bin/logisim-revolution-wrapper
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - opengl
      - unity7
      - wayland
      - x11
      - removable-media

parts:
  logisim-revolution:
    plugin: gradle
    source: .
    gradle-task: shadowJar
    gradle-parameters:
      - -x
      - test
      - --console=plain
    override-pull: |
      craftctl default
      REVOLUTION_VERSION="$(cat gradle.properties | grep '^version\s*=.*' | awk '{print $3}')"
      craftctl set version="${REVOLUTION_VERSION}"
    build-packages:
      - gradle
      - openjdk-21-jdk
    stage-packages:
      - openjdk-21-jre
    organize:
      jar/logisim-revolution-*-all.jar: jar/logisim-revolution.jar

  local-parts:
    plugin: dump
    source: ./snap/local
    source-type: local
